### ISSUE TITLE
Alternative branch/cloning approach for newcomers

### ISSUE THREAD

**Issue by bengl** [Trott/nodetodo#1]
[I forked the Getting Started gist.](https://gist.github.com/bengl/d4f52fa1abddeae7844785f5405de616)

The main difference is that the origin is https://github.com/nodejs/node.git. The reason for this is that newcomers are used to doing a `git pull` to update their local master branch. I've seen some weird mistakes with people dealing with `upstream` as it currently is in the gist (especially among those relatively new to git), and I feel like this simplifies things and reduces the mistakes.

**Comment by Trott** [comment]
This may be a good idea on some levels, but I don't know that I want to direct people to a different setup than that described in the main repo documentation. See, for example, [CONTRIBUTING.md](https://github.com/nodejs/node/blob/d6d32296039165ff3eb2cae182d97dac37a782e5/CONTRIBUTING.md#step-1-fork).

So the path forward for this might be to first get the change into all the relevant `.md` files in the main repo. And that may be an uphill battle...

What do you think?

**Comment by Trott** [comment]
I'm going to close this, but if you feel strongly about it, comment and we'll re-open and talk some more. (Might be better for the nodejs/code-and-learn repo, though. Or even nodejs/node.)

**Comment by bengl** [comment]
Yeah, I feel like this is a tabs v.s. spaces kind of issue. It's been settled and there's no sense rocking the boat here.
