### ISSUE TITLE
404 Not Found: "guide to writing tests in the Node.js project"

### ISSUE THREAD

**Issue by Heikrana** [Trott/nodetodo#15]
On the page [next-steps](https://www.nodetodo.org/next-steps/), the **link of guide to writing test is broken**.

It has changed to [doc/contributing/writing-tests.md](https://github.com/nodejs/node/blob/master/doc/contributing/writing-tests.md) whereas the link still points to [doc/guides/writing-tests.md](https://github.com/nodejs/node/blob/master/doc/guides/writing-tests.md).

Although the change will take less than a minute, but if nobody's free then I can make the change.

P.S. I love the initiative 👍🏼

**Comment by Trott** [comment]
Thank you for reporting this. It is now fixed.
